name: Mobile

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    BuildNetStandardProject:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
          
      - name: Build .NET Standard Projcet
        run: |                    
          msbuild ./AccelerometerApp/AccelerometerApp.csproj -t:restore,build -p:RestorePackagesConfig=true /verbosity:normal /p:Configuration=Release
